spring.application.name=ProductsMicroservices
server.port=8080
# kafka producer properties
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# kafka producer acknowledgment settings
# The 'acks' property controls the acknowledgment behavior of the producer. Setting it to 'all' means that the producer will wait for the full set of in-sync replicas to acknowledge the record before considering it successfully sent. This provides the highest level of durability but may result in higher latency.
# 1, 0, all
spring.kafka.producer.acks=all